# Generated by Django 4.2 on 2023-04-10 11:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('processing', models.BooleanField()),
                ('processingSuccess', models.BooleanField(null=True)),
                ('width', models.IntegerField(validators=[core.models.width_or_height_vaildator])),
                ('height', models.IntegerField(validators=[core.models.width_or_height_vaildator])),
            ],
        ),
    ]
