# Generated by Django 4.2 on 2023-04-11 10:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_file_filename_alter_file_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='height',
            field=models.IntegerField(blank=True, default=22, validators=[core.models.width_or_height_vaildator]),
        ),
        migrations.AlterField(
            model_name='file',
            name='width',
            field=models.IntegerField(blank=True, default=22, validators=[core.models.width_or_height_vaildator]),
        ),
    ]
